version: '3'
services:
  frontend:
    image: webpack
    container_name: ai-dashboard
    build:
    context: ./
    ports:
  - 3000:3000
    volumes:
  - ./:/bindmount:rw
  - node_modules:/src/node_modules
    volumes:
      node_modules:
  depends_on:
  - database
    database:
      image: cassandra:3.11.2
      container_name: ai-dashboard-cassandra
