version: '3'
services:
  web:
    container_name: ai-dashboard
    image: webpack
    build:
      context: ./
    ports:
      - 3000:3000
    depends_on:
      - database
  database:
      image: cassandra:3.11.2
      container_name: ai-dashboard-cassandra


